name: event_hub
description: "Event Hub"
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.7.0-267.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.2.1
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.0.17
  hugeicons: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  assets:
    - assets/images/
    - assets/vector/
  uses-material-design: true


