name: event_hub
description: "Event Hub"
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.7.0-267.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
